BlueVends.Presentation/Controllers/CartController.cs
using AutoMapper;
using BlueVends.Business.BusinessObjects;
using BlueVends.Business.Exceptions;
using BlueVends.Presentation.ActionFilters;
using BlueVends.Presentation.Mappers.Cart;
using BlueVends.Presentation.ViewModels;
using BlueVends.Shared.DTO.Cart;
using BlueVends.Shared.DTO.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BlueVends.Presentation.Controllers
{
    [UserAuthenticationFilter]
    public class CartController : Controller
    {
        CartBusinessContext cartBusinessContext;
        private IMapper _CartMapper;
        private IMapper _CartsMapper;
        public CartController()
        {
            cartBusinessContext = new CartBusinessContext();

            _CartMapper = AutoMappers.CartMapper;
            _CartsMapper = AutoMappers.CartsMapper;
        }

        // POST: Add item to cart
        [HttpPost]
        public ActionResult AddItem([Bind(Include = "VariantID, ProductID, OrderQuantity, OrderLimit, Inventory")] CartViewModel cartViewModel )
        {
            CartMessageViewModel cartMessageViewModel = new CartMessageViewModel();

            if (ModelState.IsValid)
            {
                CartDTO cartDTO = _CartMapper.Map<CartDTO>(cartViewModel);
                cartDTO.UserID = new Guid(Session["UserID"].ToString());
                try
                {
                    cartBusinessContext.AddItemToCart(cartDTO);
                    cartMessageViewModel.SuccessMessage = "Item Successfuly Added to Cart";
                    cartMessageViewModel.IsLoggedIn = true;
                    return View(cartMessageViewModel);
                }
                catch(ItemAlreadyInCartException ex)
                {
                    cartMessageViewModel.ErrorMessages.Add("Item is already present in the cart");
                    return View(cartMessageViewModel);
                }
                catch(Exception ex)
                {
                    return View("InternalError");
                }
            }
            else
            {
                foreach(var modelState in ModelState.Values)
                {
                    foreach(var err in modelState.Errors)
                    {
                        cartMessageViewModel.ErrorMessages.Add(err.ErrorMessage.ToString());
                    }
                }
                return View(cartMessageViewModel);
            }
        }

        
        public ActionResult ViewCart()
        {
            CartsDTO newCartsDTO = cartBusinessContext.GetCart(new Guid(Session["UserID"].ToString()));
            CartsViewModel cartsViewModel = new CartsViewModel();
            cartsViewModel.CartItems = _CartsMapper.Map<IEnumerable<CartVariantDTO>, IEnumerable<CartVariantViewModel>>(newCartsDTO.CartItems);
            cartsViewModel.CartItems = cartsViewModel.CartItems.ToList();
            cartsViewModel.SubTotal = newCartsDTO.SubTotal;
            cartsViewModel.IsLoggedIn = true;
            return View(cartsViewModel);
        }


        public ActionResult RemoveItem(Guid VariantID)
        {
            cartBusinessContext.RemoveItem(new Guid(Session["UserID"].ToString()), VariantID);
            return RedirectToAction("ViewCart");
        }
    }
}

BlueVends.Presentation/Controllers/LoginController.cs
using AutoMapper;
using BlueVends.Business.BusinessObjects;
using BlueVends.Business.Exceptions;
using BlueVends.Presentation.Mappers.Login;
using BlueVends.Presentation.ViewModels;
using BlueVends.Shared.DTO.User;
using System;
using System.Web.Mvc;

namespace BlueVends.Presentation.Controllers
{
    public class LoginController : Controller
    {

        UserBusinessContext userBusinessContext;
        IMapper _LoginMapper;
        public LoginController()
        {
            userBusinessContext = new UserBusinessContext();
            _LoginMapper = AutoMappers.LoginMapper;
        }

        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "UserName, Password" )] LoginViewModel loginViewModel)
        {

            if (ModelState.IsValid)
            {
                UserLoginDTO userLoginDTO = _LoginMapper.Map<LoginViewModel, UserLoginDTO>(loginViewModel);
                try
                {
                    UserBasicDTO loggedInUserDTO = userBusinessContext.LoginUser(userLoginDTO);
                    Session["UserID"] = loggedInUserDTO.ID;
                    if(Request.UrlReferrer.ToString() == "a") { return null; }
                    return RedirectToAction("Index", "Home");
                }
                catch(InvalidLoginException ex)
                {

                    ModelState.AddModelError("", "Invalid Login Credentials.");
                    return View(loginViewModel);
                }
                catch(Exception ex)
                {
                    ModelState.AddModelError("", "Something went wrong, Please try again.");
                    return View("Error");
                }
            }
            return View(loginViewModel);
        }
    }
}

BlueVends.Presentation/Controllers/OrderController.cs
using AutoMapper;
using BlueVends.Business.BusinessObjects;
using BlueVends.Business.Exceptions;
using BlueVends.Presentation.ActionFilters;
using BlueVends.Presentation.Mappers.Order;
using BlueVends.Presentation.ViewModels;
using BlueVends.Shared.DTO.Order;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace BlueVends.Presentation.Controllers
{
    [UserAuthenticationFilter]
    public class OrderController : Controller
    {
        OrderBusinessContext orderBusinessContext;
        IMapper _AddressMapper;
        IMapper _OrdersMapper;
        public OrderController()
        {
            orderBusinessContext = new OrderBusinessContext();
            _AddressMapper = AutoMappers.AddressMapper;
            _OrdersMapper = AutoMappers.OrdersMapper;
        }

        public OrdersDTO OrdersDTO { get; private set; }

        public ActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Checkout([Bind(Include = ("AddressLine1, AddressLine2, PIN"))] AddressViewModel addressViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    AddressDTO addressDTO = _AddressMapper.Map<AddressDTO>(addressViewModel);
                    orderBusinessContext.PlaceOrder(new Guid(Session["UserID"].ToString()), addressDTO);
                    return View("Success");
                }
                catch(Exception ex)
                {
                    return View("Internal Error");
                }
            }
            else
            {
                return View(addressViewModel);
            }
        }

        public ActionResult MyOrders()
        {
            OrdersViewModel ordersViewModel = new OrdersViewModel();
            try
            {
                OrdersDTO ordersDTO = orderBusinessContext.GetOrders(new Guid(Session["UserID"].ToString()));
                ordersViewModel.Orders = _OrdersMapper.Map<IEnumerable<OrderDTO>, IEnumerable<OrderViewModel>>(ordersDTO.Orders);
                ordersViewModel.IsLoggedIn = true;
            }
            catch(NoOrderException ex)
            {
                return View("NoOrders");
            }
            catch(Exception ex)
            {
                return View("InternalError");
            }
            return View(ordersViewModel);
        }
    }
}

BlueVends.Presentation/Controllers/UserController.cs
using AutoMapper;
using BlueVends.Business.BusinessObjects;
using BlueVends.Presentation.ActionFilters;
using BlueVends.Presentation.Mappers.User;
using BlueVends.Presentation.ViewModels;
using BlueVends.Shared.DTO.User;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace BlueVends.Presentation.Controllers
{
    [UserAuthenticationFilter]
    public class UserController : Controller
    {
        UserBusinessContext userBusinessContext = new UserBusinessContext();
        IMapper _OrdersVMMapper;
        // GET: User

        public UserController()
        {
            _OrdersVMMapper = AutoMappers.OrdersVMMapper;
        }
        public ActionResult Orders()
        {
            ViewBag.LoggedIn = "true";
            OrdersViewModel ordersViewModel = new OrdersViewModel();
            try
            {
                UserOrdersDTO newuserOrdersDTO = userBusinessContext.GetOrders(new Guid(Session["UserID"].ToString()));
                ordersViewModel.Orders = _OrdersVMMapper.Map<IEnumerable<UserOrderDTO>, IEnumerable<OrderViewModel>>(newuserOrdersDTO.Orders);
                return View(ordersViewModel);
            }
            catch(Exception ex)
            {
                return View("InternalError");
            }
        }

        public ActionResult Order(Guid orderID)
        {
            OrderViewModel orderViewModel = new OrderViewModel();
            try
            {
                UserOrderDTO newuserOrderDTO = userBusinessContext.GetOrder(orderID);
                return Json(newuserOrderDTO, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return null;
            }
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult CheckAdmin()
        {
            try
            {
                if(userBusinessContext.CheckAdmin(new Guid(Session["UserID"].ToString())))
                {
                    return View("Admin");
                }
                else
                {
                    return View("NotAdmin");
                }
            }
            catch (Exception)
            {
                return View("InternalError");
            }
        }
    }
}

BlueVends.Presentation/Views/Shared/InternalError.cshtml
@{
    ViewBag.Title = "View";
}

<h2>There was an Internal Error. Please Login and try Again.</h2>

BlueVends.Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")*@
    @*@Scripts.Render("~/bundles/modernizr")*@

    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rokkitt:100,300,400,700" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="~/Content/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/Content/icomoon.css">
    <!-- Ion Icon Fonts-->
    <link rel="stylesheet" href="~/Content/ionicons.min.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/Content/magnific-popup.css">

    <!-- Flexslider  -->
    <link rel="stylesheet" href="~/Content/flexslider.css">

    <!-- Owl Carousel -->
    <link rel="stylesheet" href="~/Content/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/owl.theme.default.min.css">

    <!-- Date Picker -->
    <link rel="stylesheet" href="~/Content/bootstrap-datepicker.css">
    <!-- Flaticons  -->
    <link rel="stylesheet" href="~/Content/flaticon.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="~/Content/style.css">
</head>
<body>
    <div class="colorlib-loader"></div>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("BlueVends", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        @if (ViewBag.LoggedIn == null)
                        {
                            <li>@Html.ActionLink("Sign-In", "Login", "Login")</li>
                            <li>@Html.ActionLink("Sign-Up", "Register", "Register")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("My Orders", "Orders", "User")</li>
                            <li>@Html.ActionLink("Sign Out", "Logout", "User")</li>
                        }
                        @using (Html.BeginForm("SearchProducts", "Products", FormMethod.Get))
                        {
                            <li>
                                @Html.TextBox("SearchString") <br />
                                <input type="submit" value="Search Products" />
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <div><h2>@ViewBag.LoggedIn</h2></div>*@



    <div class="container body-content">


        <div class="colorlib-loader"></div>
        @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>*@
        @*@Html.ActionLink("BlueVends", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
        @*<div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            @if (ViewBag.LoggedIn == null)
                            {
                                <li>@Html.ActionLink("Sign-In", "Login", "Login")</li>
                                <li>@Html.ActionLink("Sign-Up", "Register", "Register")</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("My Orders", "Orders", "User")</li>
                                <li>@Html.ActionLink("Sign Out", "Logout", "User")</li>
                            }
                            @using (Html.BeginForm("SearchProducts", "Products", FormMethod.Get))
                            {
                                <li>
                                    @Html.TextBox("SearchString") <br />
                                    <input type="submit" value="Search Products" />
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </div>*@
        @*<div><h2>@ViewBag.LoggedIn</h2></div>*@




        <div>
            <nav class="colorlib-nav" role="navigation">
                <div class="top-menu">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-7 col-md-9">
                                @Html.ActionLink("BlueVends", "Index", "Home", new { area = "" }, new { @id = "colorlib-logo" })
                            </div>
                            <div class="col-sm-5 col-md-3">

                                @using (Html.BeginForm("SearchProducts", "Products", FormMethod.Get, new { @class = "search-wrap" }))
                                {
                                    <div class="form-group">
                                        <input type="search" class="form-control search" placeholder="Search" name="SearchString">
                                        <button class="btn btn-primary submit-search text-center" type="submit"><i class="icon-search"></i></button>
                                    </div>
                                }

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12 text-left menu-1">
                                <ul>
                                    <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                                    <li><a href="@Url.Action("CategoryProducts", "Products", new { CategoryName = "Clothing" })">Clothing</a></li>
                                    <li><a href="@Url.Action("CategoryProducts", "Products", new { CategoryName = "Footwear" })">Footwear</a></li>
                                    <li><a href="@Url.Action("CategoryProducts", "Products", new { CategoryName = "Jewellery" })">Jewellery</a></li>
                                    @if (ViewBag.IsLoggedIn == null)
                                    {
                                        <li>@Html.ActionLink("Sign-In", "Login", "Login")</li>
                                        <li>@Html.ActionLink("Sign-Up", "Register", "Register")</li>
                                    }
                                    else
                                    {
                                        <li>@Html.ActionLink("My Orders", "MyOrders", "Order")</li>
                                        <li>@Html.ActionLink("Sign Out", "Logout", "User")</li>
                                    }
                                    <li class="cart"><a href="@Url.Action("ViewCart", "Cart")"><i class="icon-shopping-cart"></i> Cart </a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <hr />
        @RenderBody()


        @*<footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>*@
    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.min.js"></script>
    <!-- popper -->
    <script src="~/Scripts/popper.min.js"></script>
    <!-- jQuery easing -->
    <script src="~/Scripts/jquery.easing.1.3.js"></script>
    <!-- Waypoints -->
    <script src="~/Scripts/jquery.waypoints.min.js"></script>
    <!-- Flexslider -->
    <script src="~/Scripts/jquery.flexslider-min.js"></script>
    <!-- Owl carousel -->
    <script src="~/Scripts/owl.carousel.min.js"></script>
    <!-- Magnific Popup -->
    <script src="~/Scripts/jquery.magnific-popup.min.js"></script>
    <script src="~/Scripts/magnific-popup-options.js"></script>
    <!-- Date Picker -->
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <!-- Stellar Parallax -->
    <script src="~/Scripts/jquery.stellar.min.js"></script>
    <!-- Main -->
    <script src="~/Scripts/main.js"></script>
    <script>
        $(document).ready(function () {

            var quantitiy = 0;
            $('.quantity-right-plus').click(function (e) {

                // Stop acting like a button
                e.preventDefault();
                // Get the field name
                var quantity = parseInt($('#quantity').val());

                // If is not undefined

                $('#quantity').val(quantity + 1);


                // Increment

            });

            $('.quantity-left-minus').click(function (e) {
                // Stop acting like a button
                e.preventDefault();
                // Get the field name
                var quantity = parseInt($('#quantity').val());

                // If is not undefined

                // Increment
                if (quantity > 0) {
                    $('#quantity').val(quantity - 1);
                }
            });

        });
    </script>


    @RenderSection("scripts", required: false)
</body>
</html>