BlueVends.Presentation/ViewModels/CategoryProductsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlueVends.Presentation.ViewModels
{
    public class CategoryProductsViewModel
    {
        public string Name { get; set; }
        public bool IsLoggedIn { get; set; }
        public IEnumerable<ProductViewModel> Products;
    }
}

BlueVends.Presentation/ViewModels/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BlueVends.Presentation.ViewModels
{
    public class ProductViewModel
    {
        public bool IsLoggedIn { get; set; }
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public int Discount { get; set; }
        public int ListingPrice { get; set; }
        public int Inventory { get; set; }
        public int QuantitySold { get; set; }
        public int OrderLimit { get; set; }
        public string ImageURL { get; set; }
        public System.Guid CategoryID { get; set; }
        public IEnumerable<VariantViewModel> Variants { get; set; }
        public int DiscountedPrice { get; set; }
    }
}

BlueVends.Presentation/Controllers/CartController.cs
using AutoMapper;
using BlueVends.Business.BusinessObjects;
using BlueVends.Business.Exceptions;
using BlueVends.Presentation.ActionFilters;
using BlueVends.Presentation.Mappers.Cart;
using BlueVends.Presentation.ViewModels;
using BlueVends.Shared.DTO.Cart;
using BlueVends.Shared.DTO.Shared;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BlueVends.Presentation.Controllers
{
    [UserAuthenticationFilter]
    public class CartController : Controller
    {
        CartBusinessContext cartBusinessContext;
        private IMapper _CartMapper;
        private IMapper _CartsMapper;
        public CartController()
        {
            cartBusinessContext = new CartBusinessContext();

            _CartMapper = AutoMappers.CartMapper;
            _CartsMapper = AutoMappers.CartsMapper;
        }

        // POST: Add item to cart
        [HttpPost]
        public ActionResult AddItem([Bind(Include = "VariantID, ProductID, OrderQuantity, OrderLimit, Inventory")] CartViewModel cartViewModel )
        {
            CartMessageViewModel cartMessageViewModel = new CartMessageViewModel();

            if (ModelState.IsValid)
            {
                CartDTO cartDTO = _CartMapper.Map<CartDTO>(cartViewModel);
                cartDTO.UserID = new Guid(Session["UserID"].ToString());
                try
                {
                    cartBusinessContext.AddItemToCart(cartDTO);
                    cartMessageViewModel.SuccessMessage = "Item Successfuly Added to Cart";
                    cartMessageViewModel.IsLoggedIn = true;
                    return View(cartMessageViewModel);
                }
                catch(ItemAlreadyInCartException ex)
                {
                    cartMessageViewModel.ErrorMessages.Add("Item is already present in the cart");
                    return View(cartMessageViewModel);
                }
                catch(Exception ex)
                {
                    return View("InternalError");
                }
            }
            else
            {
                foreach(var modelState in ModelState.Values)
                {
                    foreach(var err in modelState.Errors)
                    {
                        cartMessageViewModel.ErrorMessages.Add(err.ErrorMessage.ToString());
                    }
                }
                return View(cartMessageViewModel);
            }
        }

        
        public ActionResult ViewCart()
        {
            CartsDTO newCartsDTO = cartBusinessContext.GetCart(new Guid(Session["UserID"].ToString()));
            CartsViewModel cartsViewModel = new CartsViewModel();
            cartsViewModel.CartItems = _CartsMapper.Map<IEnumerable<CartVariantDTO>, IEnumerable<CartVariantViewModel>>(newCartsDTO.CartItems);
            cartsViewModel.CartItems = cartsViewModel.CartItems.ToList();
            cartsViewModel.SubTotal = newCartsDTO.SubTotal;
            cartsViewModel.IsLoggedIn = true;
            return View(cartsViewModel);
        }


        public ActionResult RemoveItem(Guid VariantID)
        {
            cartBusinessContext.RemoveItem(new Guid(Session["UserID"].ToString()), VariantID);
            return RedirectToAction("ViewCart");
        }
    }
}

BlueVends.Presentation/Controllers/ProductsController.cs
using AutoMapper;
using BlueVends.Business.BusinessObjects;
using BlueVends.Business.Exceptions;
using BlueVends.Presentation.ActionFilters;
using BlueVends.Presentation.Mappers.Products;
using BlueVends.Presentation.ViewModels;
using BlueVends.Shared.DTO.Product;
using System;
using System.Web.Mvc;

namespace BlueVends.Presentation.Controllers
{
    public class ProductsController : Controller
    {
        ProductBusinessContext productBusinessContext = new ProductBusinessContext();
        IMapper _CategoryProductVMMapper;
        IMapper _ProductProductVMMapper;
        IMapper _ProductsSearchResultVMMapper;
        // GET: Products

        public ProductsController()
        {
            _CategoryProductVMMapper = AutoMappers.CategoryProductVMMapper;
            _ProductProductVMMapper = AutoMappers.ProductProductVMMapper;
            _ProductsSearchResultVMMapper = AutoMappers.ProductsSearchResultVMMapper;
        }

        public ActionResult CategoryProducts(string CategoryName)
        {
            
            CategoryProductsViewModel viewModel = new CategoryProductsViewModel();
            CategoryProductsDTO categoryProductsDTO = new CategoryProductsDTO();
            try
            {
                categoryProductsDTO = productBusinessContext.GetCategoryProducts(CategoryName);
            }
            catch(CategoryDoesNotExistsException ex)
            {
                return View("Error");
            }
            catch(Exception ex)
            {
                return View("Internal Error");
            }
            viewModel = _CategoryProductVMMapper.Map<CategoryProductsDTO, CategoryProductsViewModel>(categoryProductsDTO);
            if(Session["UserID"] != null)
            {
                viewModel.IsLoggedIn = true;
            }
            return View(viewModel);
        }

        [UserAuthenticationFilter]
        public ActionResult ProductDetail(Guid ProductID)
        {
            ProductViewModel viewModel = new ProductViewModel();
            ProductDTO productDTO = new ProductDTO();
            try
            {
                productDTO = productBusinessContext.GetProduct(ProductID);
            }
            catch (CategoryDoesNotExistsException ex)
            {
                return View("Error");
            }
            catch (Exception ex)
            {
                return View("Internal Error");
            }
            viewModel = _ProductProductVMMapper.Map<ProductDTO, ProductViewModel>(productDTO);
            viewModel.IsLoggedIn = true;
            return View(viewModel);

        }

        
        public ActionResult SearchProducts(string SearchString)
        {
            if (Session["UserID"] != null)
            {
                ViewBag.IsLoggedIn = "True";
            }

            if (String.IsNullOrEmpty(SearchString))
            {
                return View("Search String Empty");//TODO
            }

            ProductsSearchResultDTO newProductsSearchResultDTO = new ProductsSearchResultDTO();
            ProductsSearchResultViewModel viewModel = new ProductsSearchResultViewModel();
            try
            {
                newProductsSearchResultDTO = productBusinessContext.GetProductsWithString(SearchString);
                viewModel = _ProductsSearchResultVMMapper.Map<ProductsSearchResultDTO, ProductsSearchResultViewModel>(newProductsSearchResultDTO);
                ViewBag.SearchString = SearchString;
                return View(viewModel);
            }
            catch(Exception ex)
            {
                return View("InternalError");
            }
        }
        
    }
}

BlueVends.Presentation/Views/Products/CategoryProducts.cshtml
@model BlueVends.Presentation.ViewModels.CategoryProductsViewModel

@{
    ViewBag.Title = "";
}

<h2>View</h2>

<div>
    <h4>Products in @Model.Name  Category</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
        @Html.ActionLink("Back to List", "Index")*@
    @*@foreach(var item in Model.Products)
        {
        <div class="row">
            <div class="col-md-3" style="padding-bottom : 20px">
                <img src=@item.ImageURL height="100px" width="100px" />

            </div>
            <div class="col-md-6">
                <b>@Html.ActionLink(item.Name, "ProductDetail", new { ProductID = item.ID })</b>

                <div>Rs : @Html.DisplayFor(modelItem => item.ListingPrice)</div>
                <div>Only @Html.DisplayFor(modelItem => item.Inventory) left in Stock.</div>
            </div>
        </div>
        <br />
        }*@

    <div class="row row-pb-md">
        @foreach (var product in Model.Products)
        {
            <div class="col-md-3 col-lg-3 mb-4 text-center">
                <div class="product-entry border">
                    <a href="@Url.Action("ProductDetail", "Products", new { ProductID = product.ID})">
                        <img src = "@product.ImageURL" class="img-fluid" alt="Free html5 bootstrap 4 template" style=" height:160px;width:140px;">
                    </a>
                    <div class="desc">
                        <h2><a href="@Url.Action("ProductDetail", "Products", new { ProductID = product.ID})">@product.Name</a></h2>
                        <span class="price">$@product.ListingPrice</span>
                    </div>
                    @if(product.Discount != 0)
                    {
                        <p>Discount Available</p>
                    }
                </div>
            </div>
        }
    </div>

</p>

BlueVends.Presentation/Views/Products/ProductDetail.cshtml
@model BlueVends.Presentation.ViewModels.ProductViewModel

@{
    ViewBag.Title = "ProductDetail";
    ViewBag.IsLoggedIn = true;
}



@*<hr />
    <div class="dl-horizontal">
        <div class="row">
            <div class="col-md-4 col-md-offset-1">
                <img src=@Model.ImageURL height="150px" width="150px" />
            </div>
            <div class="col-md-6 col-md-pull-1">
                <div class="row"><b>@Model.Name</b></div>
                <div class="row">Rs @Model.ListingPrice</div>
                <div class="row"><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p></div>
                <div class="row">Discount Available : @Model.Discount %</div>
                @using (Ajax.BeginForm("AddItem", "Cart", new AjaxOptions { HttpMethod = "POST" }))
                {
                    <label>
                        Variants
                        <select class="input-select" name="variant" style="width:300px">
                            @foreach (var v in Model.Variants)
                            {
                                <option value="@v.ID">@v.Name</option>
                            }
                        </select>
                    </label>
                    <input type="Submit" value=" Add to Cart " />
                }
            </div>
        </div>
       </div>*@


<div class="colorlib-product">
    <div class="container">
        <div class="row row-pb-lg product-detail-wrap">
            <div class="col-sm-8">
                @*<div class="jumbotron">*@
                <div class="text-center" style="margin-top:50px;">
                    @*<div class="product-entry border">*@
                    <a href="#" class="prod-img">
                        <img src="@Model.ImageURL" class="img-fluid" alt="Free html5 bootstrap 4 template" style="max-height: 300px; max-width: 300px">
                    </a>
                    @*</div>*@
                </div>
                @*</div>*@
            </div>
            <div class="col-sm-4">
                <div class="product-desc">
                    <h3>@Model.Name</h3>
                    <p class="price">
                        @if (Model.Discount != 0)
                        {
                            <strike>$@Model.ListingPrice</strike><span style="display:inline">  $@((Model.ListingPrice * (100 - Model.Discount) / 100))</span>
                        }
                        else
                        {
                            <span>$@Model.ListingPrice</span>
                        }
                    </p>
                    <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.</p>
                    <p><b>The order quantity of this product is limited to @Model.OrderLimit per user.</b></p>
                    <h5>@if(Model.Inventory <= 7) { <span>Only</span>} @(Model.Inventory - Model.QuantitySold) left in stock</h5>
                    @*<div class="size-wrap">
            <div class="block-26 mb-2">
                <h4>Size</h4>
                <ul>
                    <li><a href="#">7</a></li>
                    <li><a href="#">7.5</a></li>
                    <li><a href="#">8</a></li>
                    <li><a href="#">8.5</a></li>
                    <li><a href="#">9</a></li>
                    <li><a href="#">9.5</a></li>
                    <li><a href="#">10</a></li>
                    <li><a href="#">10.5</a></li>
                    <li><a href="#">11</a></li>
                    <li><a href="#">11.5</a></li>
                    <li><a href="#">12</a></li>
                    <li><a href="#">12.5</a></li>
                    <li><a href="#">13</a></li>
                    <li><a href="#">13.5</a></li>
                    <li><a href="#">14</a></li>
                </ul>
            </div>
            <div class="block-26 mb-4">
                <h4>Width</h4>
                <ul>
                    <li><a href="#">M</a></li>
                    <li><a href="#">W</a></li>
                </ul>
            </div>
        </div>*@
                    @using (Html.BeginForm("AddItem", "Cart", new { ProductID = Model.ID, Inventory = Model.Inventory, OrderLimit = Model.OrderLimit }, FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        <div class="input-group mb-4">
                            <span class="input-group-btn">
                                <button type="button" class="quantity-left-minus btn" data-type="minus" data-field="">
                                    <i class="icon-minus2"></i>
                                </button>
                            </span>


                            <input type="text" id="quantity" name="OrderQuantity" class="form-control input-number" value="1" min="1" max="100">
                            <span class="input-group-btn ml-1">
                                <button class="quantity-right-plus btn" type="button" data-type="plus" data-field="">
                                    <i class="icon-plus2"></i>
                                </button>
                            </span>
                            <select name="VariantID" id="variant" class="form-control">
                                @foreach (var Variant in Model.Variants)
                                {
                                    <option value=@Variant.ID>@Variant.Name</option>
                                    }
                            </select>
                        </div>

                        <div class="row">
                            <div class="col-sm-12 text-center">
                                <p class="addtocart"><button class="btn btn-primary btn-addtocart" type="submit"><i class="icon-shopping-cart"></i> Add to Cart</button></p>
                            </div>
                        </div>
                    }
                    <div id="Target"></div>
                </div>
            </div>
        </div>
    </div>
</div>

BlueVends.Presentation/Views/Products/SearchProducts.cshtml
@model BlueVends.Presentation.ViewModels.ProductsSearchResultViewModel

@{
    ViewBag.Title = "SearchProducts";
}

<h2>Search Results</h2>

<div>
    <h4>Your search " @ViewBag.SearchString "</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
</div>
<p>
    <div class="row row-pb-md">
        @foreach (var product in Model.Products)
        {
            <div class="col-md-3 col-lg-3 mb-4 text-center">
                <div class="product-entry border">
                    <a href="@Url.Action("ProductDetail", "Products", new { ProductID = product.ID})">
                        <img src="@product.ImageURL" class="img-fluid" alt="Free html5 bootstrap 4 template" style=" height:160px;width:140px;">
                    </a>
                    <div class="desc">
                        <h2><a href="@Url.Action("ProductDetail", "Products", new { ProductID = product.ID})">@product.Name</a></h2>
                        <span class="price">$@product.ListingPrice</span>
                    </div>
                    @if(product.Discount != 0)
                    {
                        <p>Discount Available</p>
                    }
                </div>
            </div>
        }
    </div>
</p>